### ISSUE TITLE
ImportError: No module named 'urllib2'

### ISSUE THREAD

**Issue by evandrocoan** [noahcoad/google-spell-check#29]
Related issue:

1. https://github.com/noahcoad/google-spell-check/issues/12 ImportError: No module named 'urllib2'

On that issue they mention there is not mention of the `urllib2` on the ST3 branch, however now there is:

![image](https://user-images.githubusercontent.com/5332158/27955756-b1343e4e-62ec-11e7-8375-adc6ad5c3b06.png)

And it is throwing this error every time I start Sublime Text build 3141:
```
reloading plugin Google Spell Check.google-spell-check
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\Google Spell Check\google-spell-check.py", line 4, in <module>
    import sublime, sublime_plugin, urllib2, re, HTMLParser
ImportError: No module named 'urllib2'
```
Also this plugin is not working anymore:

![image](https://user-images.githubusercontent.com/5332158/27955782-dc721824-62ec-11e7-86ec-5265ab2b3ca3.png)

**Comment by evandrocoan** [comment]
I was on the branch master, which contains some unknown version. Switched to the branch st3 fixed the problem.
